---
- name: Teknoir Notebook Example Playbook
  hosts: all
  vars:
    project_id: "{{ lookup('env','PROJECT_ID') }}"
    ns: "{{ lookup('env','NAMESPACE') }}"
    branch_name: "{{ lookup('env','BRANCH_NAME') }}"
    short_sha: "{{ lookup('env','SHORT_SHA') }}"
    location: us-central1
  tasks:
    - name: Ensure tmp ansible dir
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/tmp/ansible
        state: directory
        mode: '0755'

    - name: Ensure local tmp ansible dir
      delegate_to: localhost
      ansible.builtin.file:
        path: ./tmp/ansible
        state: directory
        mode: '0755'

    - name: Copy ansible dir to remote host
      ansible.builtin.synchronize:
        use_ssh_args: true
        src: ./
        dest: /home/{{ ansible_user }}/tmp/ansible/
        recursive: yes
        delete: yes
        rsync_opts:
          - --include=*.yaml
          - --include=*.cfg
          - --include=*.sh
          - --include=*.py
          - --include=*.md
          - --exclude=*

    - name: Copy ansible dir back to local
      ansible.builtin.synchronize:
        use_ssh_args: true
        src: /home/{{ ansible_user }}/tmp/ansible/
        dest: ./tmp/ansible/
        recursive: yes
        delete: yes
        mode: pull
        rsync_opts:
          - --include=*.yaml
          - --include=*.cfg
          - --include=*.sh
          - --include=*.py
          - --include=*.md
          - --exclude=*

    - name: Get the dist info
      shell: "uname -a"
      register: distinfo

    - name: Some other op
      shell: "ls -la"

    - name: Display the dist info
      debug: msg="{{ distinfo.stdout }}"
