---
- name: Teknoir Notebook Playbook
  hosts: all

  tasks:
  - name: Install required python packages
    pip:
      name:
        - minimal

  - name: Create tmp dir
    ansible.builtin.file:
      path: "{{home}}/tmp"
      state: directory

  - name: Copy hello.sh to host, and make it executable
    ansible.builtin.copy:
      src: files/hello.sh
      dest: "{{home}}/tmp/hello.sh"
      mode:  u+rwx,g+rwx,o-wx

  - name: Run hello.sh
    ansible.builtin.command: "{{home}}/tmp/hello.sh"
